### ISSUE TITLE
Root API url without trailing slash location is missing in resource URL

### ISSUE THREAD

**Issue by dspechnikov** [allisson/python-simple-rest-client#11]
### How to reproduce
1. Initialize API url with root URL with a location segment, but without trailing slash, i.e.:
```python
API(api_root_url='https://test.loc/api')
```
2. Add a resource.
3. Invoke any method of the resource.

### Expected result
I expect one of 2 options:
1. A resource URL uses root URL with trailing slash (i.e. `https://test.loc/api/resource`).
2. An exception is raised pointing to wrong configuration.

I like the first one a lot better. If there are any objections, please shout.

### Actual result
A resource URL without root URL path is used, i.e. `https://test.loc/resource`.

### Root cause
[This](https://github.com/allisson/python-simple-rest-client/blob/ffb53d0f42630b79ad544a5b53578b0389dcb120/simple_rest_client/resource.py#L75) line.

**Comment by dagostinelli** [comment]
This isn't working for me.  I'm getting double-slashes on all my API URLs now.  My resource URLs all start with a slash so that I can use absolute paths.  Now that simple-rest-client is appending a slash to the root URL, I get double slashes.  The result is a 404 every time.

```
class MyResource(Resource):
	actions = {
		'make_apple': {'method': 'GET', 'url': '/orchard/make_apple'},
	}
```

```
simple_rest_client.exceptions.NotFoundError: ("operation=not_found_error, response=Response(url='http://127.0.0.1:5000//orchard/make_apple', method='GET', body={'error': 404, 'text': '404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.'}
```

The work around is to remove the leading slash on all the resources (pain). 

(A little while ago, I upgraded from PyPI and received this change in there. )

**Comment by allisson** [comment]
@dagostinelli check if work with https://pypi.org/project/simple-rest-client/0.5.4/ :smiley:
